// ----------------------------------------------------------------------------
// OpenSDSE - HLA Compliant Distributed Aircraft Simulation
// Copyright (C) 2017  ISAE
//
// This program is free software ; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation ; either version 2 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY ; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program ; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
//
// ----------------------------------------------------------------------------

#include "DataLogger.hh"
#include <iostream>
#include <cmath>
#include <ctime>
#include <cstdlib>

// ----------------------------------------------------------------------------
DataLogger::DataLogger() 
{
	 TRIM_DATA_RIGHT_ENGINE_THRUST_EQ =0.0 ;
	 TRIM_DATA_LEFT_ENGINE_THRUST_EQ =0.0 ;
	 TRIM_DATA_RIGHT_ENGINE_THROTTLE_EQ =0.0 ;
	 TRIM_DATA_LEFT_ENGINE_THROTTLE_EQ =0.0 ;
     TRIM_DATA_ELEVATOR_DEFLECTION_EQ =0.0 ;
     TRIM_DATA_STABILIZER_DEFLECTION_EQ =0.0 ;

	 JOYSTICK_AILERON =0.0 ;
	 JOYSTICK_ELEVATOR =0.0 ;
	 JOYSTICK_RUDDER =0.0 ;
	 JOYSTICK_THROTTLE_LEFT = 0.0 ;
	 JOYSTICK_THROTTLE_RIGHT = 0.0 ;
     JOYSTICK_FLAPS = 0.0;
     JOYSTICK_SPOILERS = 0.0;
     JOYSTICK_GEARS = 0.0;
     JOYSTICK_BRAKES = 0.0;

	 FLIGHT_CONTROLS_RIGHT_AILERON_COMMANDED_DEFLECTION =0.0 ;
	 FLIGHT_CONTROLS_LEFT_AILERON_COMMANDED_DEFLECTION =0.0 ;
	 FLIGHT_CONTROLS_RIGHT_ELEVATOR_COMMANDED_DEFLECTION =0.0 ;
	 FLIGHT_CONTROLS_LEFT_ELEVATOR_COMMANDED_DEFLECTION =0.0 ;
	 FLIGHT_CONTROLS_RUDDER_COMMANDED_DEFLECTION =0.0 ;
	 FLIGHT_CONTROLS_RIGHT_ENGINE_COMMANDED_THROTTLE =0.0 ;
	 FLIGHT_CONTROLS_LEFT_ENGINE_COMMANDED_THROTTLE =0.0 ;
     FLIGHT_CONTROLS_FLAPS_COMMANDED_DEFLECTION = 0.0;
     FLIGHT_CONTROLS_SPOILERS_COMMANDED_DEFLECTION = 0.0;
     FLIGHT_CONTROLS_STABILIZER_COMMANDED_DEFLECTION =0.0;
     FLIGHT_CONTROLS_GEARS_COMMANDED_POSITION =0.0;

	 ACTUATORS_RIGHT_AILERON_EFFECTIVE_DEFLECTION =0.0 ;
	 ACTUATORS_LEFT_AILERON_EFFECTIVE_DEFLECTION =0.0 ;
	 ACTUATORS_RIGHT_ELEVATOR_EFFECTIVE_DEFLECTION =0.0 ;
	 ACTUATORS_LEFT_ELEVATOR_EFFECTIVE_DEFLECTION =0.0 ;
	 ACTUATORS_RUDDER_EFFECTIVE_DEFLECTION =0.0 ;
	 ACTUATORS_RIGHT_ENGINE_THRUST =0.0 ;
	 ACTUATORS_LEFT_ENGINE_THRUST =0.0 ;
     ACTUATORS_FLAPS_EFFECTIVE_DEFLECTION =0.0;
     ACTUATORS_SPOILERS_EFFECTIVE_DEFLECTION = 0.0;
     ACTUATORS_STABILIZER_EFFECTIVE_DEFLECTION =0.0;
     ACTUATORS_GEARS_POSITION =0.0;

	 AIRCRAFT_POSITION_LONGITUDE =0.0 ;
	 AIRCRAFT_POSITION_LATITUDE =0.0 ;
	 AIRCRAFT_POSITION_ALTITUDE =0.0 ;

	 AIRCRAFT_ORIENTATION_PHI =0.0 ;
	 AIRCRAFT_ORIENTATION_THETA =0.0 ;
	 AIRCRAFT_ORIENTATION_PSI =0.0 ;

	 AIRCRAFT_UVW_SPEED_U_SPEED =0.0 ;
	 AIRCRAFT_UVW_SPEED_V_SPEED =0.0 ;
	 AIRCRAFT_UVW_SPEED_W_SPEED =0.0 ;

	 AIRCRAFT_PQR_ANGULAR_SPEED_P_ANG_SPEED =0.0 ;
	 AIRCRAFT_PQR_ANGULAR_SPEED_Q_ANG_SPEED =0.0 ;
	 AIRCRAFT_PQR_ANGULAR_SPEED_R_ANG_SPEED =0.0 ;

	 AIRCRAFT_ACCELERATION_X_ACC =0.0 ;
	 AIRCRAFT_ACCELERATION_Y_ACC =0.0 ;
	 AIRCRAFT_ACCELERATION_Z_ACC =0.0 ;

	 AIRCRAFT_SPEED_INDICATED_AIRSPEED =0.0 ;
	 AIRCRAFT_SPEED_EQUIVALENT_AIRSPEED =0.0 ;
	 AIRCRAFT_SPEED_CALIBRATED_AIRSPEED =0.0 ;
	 AIRCRAFT_SPEED_TRUE_AIRSPEED =0.0 ;
	 AIRCRAFT_SPEED_GROUND_SPEED =0.0 ;
	 AIRCRAFT_SPEED_VERTICAL_SPEED =0.0 ;
	 AIRCRAFT_SPEED_MACH_NUMBER =0.0 ;

	 AIRCRAFT_ADDITIONAL_ALPHA =0.0 ;
	 AIRCRAFT_ADDITIONAL_BETA =0.0 ;
	 AIRCRAFT_ADDITIONAL_DYNAMIC_PRESSURE =0.0 ;
     AIRCRAFT_ADDITIONAL_TANK_FILLING =0.0;

	 MEAS_AIRCRAFT_POSITION_MEAS_LONGITUDE =0.0 ;
	 MEAS_AIRCRAFT_POSITION_MEAS_LATITUDE =0.0 ;
	 MEAS_AIRCRAFT_POSITION_MEAS_ALTITUDE =0.0 ;

	 MEAS_AIRCRAFT_ORIENTATION_MEAS_PHI =0.0 ;
	 MEAS_AIRCRAFT_ORIENTATION_MEAS_THETA =0.0 ;
	 MEAS_AIRCRAFT_ORIENTATION_MEAS_PSI =0.0 ;

	 MEAS_AIRCRAFT_UVW_SPEED_MEAS_U_SPEED =0.0 ;
	 MEAS_AIRCRAFT_UVW_SPEED_MEAS_V_SPEED =0.0 ;
	 MEAS_AIRCRAFT_UVW_SPEED_MEAS_W_SPEED =0.0 ;

	 MEAS_AIRCRAFT_PQR_ANGULAR_SPEED_MEAS_P_ANG_SPEED =0.0 ;
	 MEAS_AIRCRAFT_PQR_ANGULAR_SPEED_MEAS_Q_ANG_SPEED =0.0 ;
	 MEAS_AIRCRAFT_PQR_ANGULAR_SPEED_MEAS_R_ANG_SPEED =0.0 ;

	 MEAS_AIRCRAFT_ACCELERATION_MEAS_X_ACC =0.0 ;
	 MEAS_AIRCRAFT_ACCELERATION_MEAS_Y_ACC =0.0 ;
	 MEAS_AIRCRAFT_ACCELERATION_MEAS_Z_ACC =0.0 ;

	 MEAS_AIRCRAFT_SPEED_MEAS_INDICATED_AIRSPEED =0.0 ;
	 MEAS_AIRCRAFT_SPEED_MEAS_EQUIVALENT_AIRSPEED =0.0 ;
	 MEAS_AIRCRAFT_SPEED_MEAS_CALIBRATED_AIRSPEED =0.0 ;
	 MEAS_AIRCRAFT_SPEED_MEAS_TRUE_AIRSPEED =0.0 ;
	 MEAS_AIRCRAFT_SPEED_MEAS_GROUND_SPEED =0.0 ;
	 MEAS_AIRCRAFT_SPEED_MEAS_VERTICAL_SPEED =0.0 ;
	 MEAS_AIRCRAFT_SPEED_MEAS_MACH_NUMBER =0.0 ;

	 MEAS_AIRCRAFT_ADDITIONAL_MEAS_ALPHA =0.0 ;
	 MEAS_AIRCRAFT_ADDITIONAL_MEAS_BETA =0.0 ;
	 MEAS_AIRCRAFT_ADDITIONAL_MEAS_DYNAMIC_PRESSURE =0.0 ;
     MEAS_AIRCRAFT_ADDITIONAL_MEAS_TANK_FILLING =0.0;

	 ENVIRONMENT_VARIABLES_TEMPERATURE =0.0 ;
	 ENVIRONMENT_VARIABLES_DENSITY_OF_AIR =0.0 ;
	 ENVIRONMENT_VARIABLES_PRESSURE =0.0 ;
	 ENVIRONMENT_VARIABLES_SPEED_OF_SOUND =0.0 ;

	 WIND_COMPONENTS_U_WIND =0.0 ;
	 WIND_COMPONENTS_V_WIND =0.0 ;
	 WIND_COMPONENTS_W_WIND =0.0 ;
	 WIND_COMPONENTS_P_WIND =0.0 ;
	 WIND_COMPONENTS_Q_WIND =0.0 ;
	 WIND_COMPONENTS_R_WIND =0.0 ;
}
// ----------------------------------------------------------------------------
DataLogger::~DataLogger()
{

}
